- name: Install jrnl with pipx
  command: "pipx install --force --spec='jrnl[encrypted]' jrnl"
  args:
    creates: "{{dotfiles_user_home}}/.local/pipx/venvs/jrnl"
  tags:
    - pipx

- name: Symlink jrnl config file
  file:
    src: "{{ dotfiles_home }}/roles/jrnl/files/jrnl_config"
    dest: "{{ dotfiles_user_home}}/.jrnl_config"
    state: link
