- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- name: Symlink dotfiels
  file:
    src: "{{ dotfiles_home }}/roles/direnv/files/direnv"
    dest: "{{dotfiles_user_home}}/.config/direnv"
    state: link