- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- name: Symlink dotfiels
  file:
    src: "{{ dotfiles_home }}/roles/tig/files/tig"
    dest: "{{dotfiles_user_home}}/.config/tig"
    state: link